### ISSUE TITLE
Definition for "grill" does not appear

### ISSUE THREAD

**Issue by hallzy** [tuanlc/oxford-CLI#1]
I was looking up "grill" today and it came up with "Opp! No results". That word does exist on the website and appears to also work with the API.

I think I have tracked down the problem to line 28:

```python
pronunciationsStr = 'Pronunciations: ' + lexicalEntrie['pronunciations'][0]['phoneticSpelling'] + '\n'
```

Specifically, `lexicalEntrie['pronunciations']` does not appear to be working as intended for that one word... That is the only word I have come across so far that does this.

I can't look at it in any more detail at the moment so that is all the information I have at the moment apart from the fact that other words work... for instance, barbecue is working right now, so it isn't a problem with my internet connection.

**Comment by tuanlc** [comment]
Thank you for your feedback and I'm so glad when you use my application.
I will take a look and try to figure out the trouble in your case and answer you as soon as possible.

**Comment by hallzy** [comment]
Cool, Thanks :) And not a problem. It is a nifty little application. Saves me time when I can just go to the terminal instead of googling it.

If I find anything I will be sure to come back and let you know. Just need to find some spare time.

**Comment by hallzy** [comment]
Maybe it is just me, but when I look at the JSON returned by the API for the word "grill" the JSON looks kind of messed up. Like, it seems to have one of the pronunciations where it shouldn't be.

ie: for grill the pronunciation is here:

```
results -> lexicalentries -> 0 -> entries -> 0 -> pronunciation
```

But it is messed up only for the noun of grill, not the verb.

as opposed to being where your script assumes it is, and where it is for almost every word which is here:

```
results ->lexicalentries -> 0 -> pronunciations
```

So on the plus side, I would say there isn't a bug in your script. Oxford seems to have just been inconsistent in their api for whatever reason. So i guess if what I have found is true you could choose to ignore this and probably tell oxford about it, or add some sort of `try/except` clause for this weird case... Either way, I have reported the issue on the oxford api website. I will let you know if anyone gets back to me (or you could submit it yourself as well).

One way the script could try to handle this problem in the future though is to add `try/except` statements around every line of code that gets data... for example:

```python
try:
    pronunciationsStr = 'Pronunciations: ' + lexicalEntrie['pronunciations'][0]['phoneticSpelling'] + '\n'
except:
    pronunciationsStr = 'Pronunciations: N/A\n'
```

Not ideal, but in this way at least we will see which part went wrong because the data will be missing, and we can still get some data. For example, adding the above 4 lines to the script lets grill output all the information about grill, except for the pronunciation of the noun.

Up to you, but that is what i found. If you would rather not handle that error, or have a better way to do it by all means do that instead.

**Comment by tuanlc** [comment]
Awesome!
I will try your way.
Anyway, the my current code is not clean enough for reading and debugging. I have to refactor a lot of and need to read more from Oxford APIs to improve this application.
If you have any idea and or requirement, please tell me.
Thanks you for your investigation and suggestion.

**Comment by hallzy** [comment]
I didn't find the code that hard to understand actually.

Also oxford just got back to me. All they said is that "Grill" should have a pronunciation element in the same place as other entries, and to provide some screenshots showing otherwise. Seemed like an odd response since it kind of sounds like they haven't actually tried looking at their json yet but whatever. They asked for some screenshots so I just sent them 2 screenshots of the relevant areas of the json, along with the full json output, and the first few lines of your script that actually gets the json that I sent them in the first place.

I will let you know when they get back to me again.

**Comment by hallzy** [comment]
I have heard back from oxford now and they say that it was by design. This is there full response

> When you compare the data with ODO, you see that this second homograph has been rolled into the noun senses. This is why the ‘pronunciation’ element sits inside ‘entries’, parallel to the ‘senses’ element so that, structurally, it applies to the first ‘senses’ element within ‘entries’ but not the second (the variant of ‘grille’, which didn’t previously have any pronunciation content). However, with the verb senses, the ‘pronunciation’ element applies to everything within the ‘entries’ element and so it is found parallel to ‘entries’; this saves repetition for each ‘senses’ element (even though that isn’t the case in this instance).

 

> In summary, it will be necessary for you to ensure your code allows for ‘pronunciation’ elements in both positions, because where they appear will depend on how they relate to the senses within.

So it looks like this script may need to be modified to allow for both locations.

**Comment by tuanlc** [comment]
Solved. Thanks, @hallzy !
